internal;
proxy_pass_request_body off;      # Do not forward request body
proxy_set_header Content-Length "";
proxy_set_header X-Original-URI $request_uri;
proxy_set_header Authorization $http_authorization;  # Forward user token to service A
proxy_cache auth_cache;
proxy_cache_key $http_authorization;
proxy_cache_valid 200 30s;
proxy_cache_valid any 0s;