# Inject user/tenant info returned from service A into forwarding headers
# proxy_set_header X-User-Id $upstream_http_x_user_id;
# proxy_set_header X-Tenant   $upstream_http_x_tenant;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;

# Common required headers
proxy_ssl_server_name on;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;

# Long connection timeout should be large
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
send_timeout       3600s;

# Disable buffering
proxy_buffering off;
proxy_request_buffering off;